routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//multi language
Route::get('locale', function () {
    return \App::getLocale();
});

Route::get('/locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
});
//
Route::get('/about-cms/section-one', function () {
    return view('cms.about.sectionone');
});
Route::get('/about-cms/section-two', function () {
    return view('cms.about.sectiontwo');
});
Route::get('/about-cms', function () {
    return view('cms.about.about');
});
Route::get('/thankyou', function () {
    return view('front.thanks');
});

Route::get('/', function () {
    // return view('front.comingsoon');
    
    return redirect('home');
});

//front
Route::get('front/{home}', 'FrontController@index');
Route::get('about', 'AboutController@index');
Route::get('home/{home}', 'FrontController@index');
Route::get('/subcategory/{home}', 'CatalogController@subcategory');
Route::get('/category/{home}', 'CatalogController@category');
Route::get('/index/{title}', 'CatalogController@index');
//Route::post('/searchproduct', 'CatalogController@searchproduct');
Route::resource('home','FrontController');
Route::resource('blog','BlogController');
Route::resource('events','EventFrontController');
Route::resource('shop','CatalogController');
Route::resource('catalog','ProductCatalogController');

Route::get('/thanks', function () {
    return view('front.emailthanks');
});
Route::post('send','MailController@send');

Route::get('blog-user', 'PostArticleController@index');
Route::post('sendarticle','PostArticleController@send');
//auth
Auth::routes();
Route::get('/changePassword','ChangePasswordController@showChangePasswordForm');
Route::post('/changePassword','ChangePasswordController@changePassword')->name('changePassword');

//cms
Route::resource('slide','SlideController');
Route::resource('article','ArticleController');
Route::resource('event','EventController');
Route::resource('product','ProductController');
Route::resource('photo','PhotoController');
Route::get('/getsubcategory/{test}','HomeController@getsubcategory');
Route::get('/cms', function () {
    if(Auth::user()->role == 1)
    {
        return redirect('home');
    }
    else
    {
        return view('cms.dashboard');
    }
})->middleware('auth');
//

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //
    protected $table = 'articles';
    protected $fillable = [
        'number',
        'title',
        'article',
        'judul',
        'isi',
        'photo',
        'approved',
        'status', // 0 = draft, 1 = published not approved, 2 = publish approved
        'user_id',
        'readby'
    ];
    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Article;
use App\Repositories\Repository;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $model;
    public function __construct(Article $slide)
    {
        $this->middleware('auth');
        $this->model = new Repository($slide);
    }
    public function index()
    {
        //
        if(Auth::user()->role == 1)
        {
            return redirect('home');
        }
        else
        {
        $datas = $this->model->all();
        return view('cms.article.listArticle')->with('datas',$datas);
        }
         
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('cms.article.createArticle');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $this->model->create($request->all());;
        if($request->file('photo'))
        {
            $image = $request->file('photo');
            $new_name = $data->id."-" .$image->getClientOriginalName();
            //$image->move(public_path("image/article"),$new_name);
            $image->move("image/article",$new_name);
            $data->photo = $new_name ;
            $data->save();
        }
        else
        {
            $data->photo = 'default.png' ;
            $data->save();
        }
        return redirect()->route('article.index')->with('success','Article added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $data = $this->model->show($id);
        
        return view('cms.article.showArticle')->with('data',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = $this->model->show($id);
        return view('cms.article.editArticle')->with('data',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->model->update($request->all(),$id);
        if($request->file('photo'))
        {
            $data = $this->model->show($id);
            $image = $request->file('photo');
            $new_name = $data->id."-" .$image->getClientOriginalName();
           // $image->move(public_path("image/article"),$new_name);
            $image->move("image/article",$new_name);
            $data->photo = $new_name ;
            $data->save();
        }
        return redirect()->route('article.index')->with('success','Article updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $this->model->delete($id);
        return redirect()->route('article.index')->with('success','Article deleted successfully.');

    }
}

resources/views/cms/article/createArticle.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Article</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Create Article
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Create New Post</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
						</div>
						<div class="card-body collapse in">
            <form action="{{ route('article.store') }}" method="POST" enctype="multipart/form-data">
              <input type="hidden" value="{{csrf_token()}}" name="_token" />
              <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
              <div class="card-block card-dashboard">
                <label>Photo</label>
                <input name="photo" type="file" />
              </div>
              <div class="card-block card-dashboard">			
                <div class="col-md-12">
                  <fieldset>
                    <input type="checkbox" id="input-16" name="status" value=1>
                    <label for="input-16">Pubished?</label>
                  </fieldset> 
                  <fieldset class="form-group">
                      <label><strong>TITLE IN BAHASA</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="judul">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>CONTENT IN BAHASA</strong></label>
                    <textarea id="konten" class="form-control" name="isi"></textarea>
                  </fieldset> 
                  <fieldset class="form-group">
                      <label><strong>TITLE IN ENGLISH</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="title">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>CONTENT IN ENGLISH</strong></label>
                    <textarea id="article" class="form-control" name="article"></textarea>
                  </fieldset> 
                  <button type="submit" class="btn btn-primary">Submit</button>	
                </div>
							</div>
              </form>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>

    <script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>
    
    <script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('app-assets/js/scripts/forms/switch.js') }}" type="text/javascript"></script>
    <script>
    var konten = document.getElementById("konten")
      CKEDITOR.replace(konten,{
      language:'en-gb'
    })
    CKEDITOR.config.allowedContent = true
    var article = document.getElementById("article")
      CKEDITOR.replace(article,{
      language:'en-gb'
    })
    CKEDITOR.config.allowedContent = true
</script>
@endsection

resources/views/cms/article/editArticle.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Article</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Edit Article
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">{{$data->judul}}</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
						</div>
						<div class="card-body collapse in">
             <form action="{{ route('article.update',$data->id) }}" method="POST" enctype="multipart/form-data">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <input type="hidden" name="_method" value="PUT">
              <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
              <div class="card-block card-dashboard">
                
                <img src="/image/article/{{$data->photo}}" alt="" width="500" height="300">
                </br>
                <input name="photo" type="file" />
              </div>
              <div class="card-block card-dashboard">			
                <div class="col-md-12">
                  <fieldset>
                    <input type="checkbox" id="input-16" name="status" value=1 {{$data->status == 1 ? 'checked' :''}}>
                    <label for="input-16">Pubished?</label>
                  </fieldset> 
                  <fieldset>
                    <input type="checkbox" id="input-16" name="approved" {{Auth::user()->role == 3 ? '' :'disabled'}} value=1 {{$data->approved == 1 ? 'checked' :''}}>
                    <label for="input-16">Approved</label>
                  </fieldset> 
                  <fieldset class="form-group">
                      <label><strong>TITLE in bahasa</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="judul" value="{{$data->judul}}">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>CONTENT in bahasa</strong></label>
                    <textarea id="konten" class="form-control" name="isi">{!!$data->isi!!}</textarea>
                  </fieldset> 
                  <fieldset class="form-group">
                      <label><strong>TITLE in english</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="title" value="{{$data->title}}">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>CONTENT in english</strong></label>
                    <textarea id="article" class="form-control" name="article">{!!$data->article!!}</textarea>
                  </fieldset> 
                  <button type="submit" class="btn btn-primary">Save</button>	
                </div>
							</div>
              </from>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>

    <script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>
    
    <script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('app-assets/js/scripts/forms/switch.js') }}" type="text/javascript"></script>
    <script>
    var konten = document.getElementById("konten")
      CKEDITOR.replace(konten,{
      language:'en-gb'
    })
    CKEDITOR.config.allowedContent = true
    var article = document.getElementById("article")
      CKEDITOR.replace(article,{
      language:'en-gb'
    })
    CKEDITOR.config.allowedContent = true
</script>
@endsection

resources/views/cms/article/listArticle.blade.php
@extends('layouts.cms')

@section('content')
<style>
.switch {
  position: relative;
  display: inline-block;
  width: 50px;
  height: 24px;
}

.switch input { 
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 16px;
  width: 16px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Article</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">List Article
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">List Article</h4><br>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
              <a href="{{ route('article.create') }}" class="btn btn-primary">Add Article</a>	
						</div>
						<div class="card-body collapse in">
                        <div class="card-block card-dashboard">
                            <table class="table table-striped table-responsive">
                                <thead>
                                    <tr>
                                    <td colspan=2></td>
                                    <td>No</td>
                                    <td>Title</td>
                                    <td>Created By</td>
                                    <!-- <td>Approved</td> -->
                                    <td>Status</td>
                                    <td>Approve?</td>
                                    </tr>
                                </thead>
                                <tbody>
                                
                                    @foreach($datas as $data)
                                    <tr>
                                        <td><button type="button" class="btn btn-warning"><a style="font-weight: 600; color: white"href="{{ URL::to('article/' . $data->id . '/edit') }}">Edit</a></button></td>
                                        <td>
                                        <form action="{{ route('article.destroy', $data->id) }}" method="post">
                                            {{ csrf_field() }}{{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                        </td>
                                        <td>{{$loop->index+1}}</td>
                                        <td><a href="{{ URL::to('article/' . $data->id) }}">{{$data->judul}}</a></td>
                                        <td>{{$data->user->name}}</td>
                                        <!-- <td>{!!$data->isi!!}</td> -->
                                        <td>{{$data->status == 1 ? 'Published' : 'Not Published'}}</td>
                                        @if(Auth::user()->role==3)
                                        <form action="{{ route('blog.update',$data->id) }}" method="POST" enctype="multipart/form-data">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="hidden" name="_method" value="PUT">
                                        <td>
                                            <!-- <label class="switch"> -->
                                                <input type="submit" value="{{$data->approved == 1 ? 'Approved' : 'Waiting'}}" name="" class="btn btn-{{$data->approved == 1 ? 'primary' : 'danger'}}" >
                                                <input type="hidden" name="id" value="{{$data->id}}">
                                                <!-- <span class="slider round"></span> -->
                                            <!-- </label> -->
                                        </td>
                                        </form>
                                        @else
                                         <td>{{$data->approved == 1 ? 'Approved' : 'Waiting'}}</td>
                                        @endif
                                        </tr>
                                        
                                    @endforeach                                        
                                </tbody>
                            </table>
                        </div>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
@endsection

resources/views/cms/article/showArticle.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Article</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Show Article
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">{{$data->judul}}</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
						</div>
						<div class="card-body collapse in">
							
                        <div class="card-block card-dashboard">
                            <img src="/image/article/{{$data->photo}}" alt="" width="800" height="400">
                        </div>
                        <div class="card-block card-dashboard">
                            <label for="title">{!!$data->isi!!}</label>
                        </div>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
    

@endsection