routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//multi language
Route::get('locale', function () {
    return \App::getLocale();
});

Route::get('/locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
});
//
Route::get('/about-cms/section-one', function () {
    return view('cms.about.sectionone');
});
Route::get('/about-cms/section-two', function () {
    return view('cms.about.sectiontwo');
});
Route::get('/about-cms', function () {
    return view('cms.about.about');
});
Route::get('/thankyou', function () {
    return view('front.thanks');
});

Route::get('/', function () {
    // return view('front.comingsoon');
    
    return redirect('home');
});

//front
Route::get('front/{home}', 'FrontController@index');
Route::get('about', 'AboutController@index');
Route::get('home/{home}', 'FrontController@index');
Route::get('/subcategory/{home}', 'CatalogController@subcategory');
Route::get('/category/{home}', 'CatalogController@category');
Route::get('/index/{title}', 'CatalogController@index');
//Route::post('/searchproduct', 'CatalogController@searchproduct');
Route::resource('home','FrontController');
Route::resource('blog','BlogController');
Route::resource('events','EventFrontController');
Route::resource('shop','CatalogController');
Route::resource('catalog','ProductCatalogController');

Route::get('/thanks', function () {
    return view('front.emailthanks');
});
Route::post('send','MailController@send');

Route::get('blog-user', 'PostArticleController@index');
Route::post('sendarticle','PostArticleController@send');
//auth
Auth::routes();
Route::get('/changePassword','ChangePasswordController@showChangePasswordForm');
Route::post('/changePassword','ChangePasswordController@changePassword')->name('changePassword');

//cms
Route::resource('slide','SlideController');
Route::resource('article','ArticleController');
Route::resource('event','EventController');
Route::resource('product','ProductController');
Route::resource('photo','PhotoController');
Route::get('/getsubcategory/{test}','HomeController@getsubcategory');
Route::get('/cms', function () {
    if(Auth::user()->role == 1)
    {
        return redirect('home');
    }
    else
    {
        return view('cms.dashboard');
    }
})->middleware('auth');
//

app/Events.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Events extends Model
{
    //
    protected $table = 'events';
    protected $fillable = [
        'number',
        'title',
        'desc',
        'photo',
        'status',
        'judul',
        'deskripsi',
        'datelive',
        'dateend'
    ];
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use App\Events;
use App\Repositories\Repository;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $model;
    public function __construct(Events $events)
    {
        $this->middleware('auth');
        $this->model = new Repository($events);
    }
    public function index()
    {
        //
        if(Auth::user()->role == 1)
        {
            return redirect('home');
        }
        else
        {
            $datas = $this->model->all();
            return view('cms.event.event')->with('datas',$datas);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = $this->model->show($id);
        return view('cms.event.editevent')->with('data',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data = $this->model->show($id);
        $data->title = $request->title;
        $data->status = 1;
        $data->desc = $request->desc;
        $data->deskripsi = $request->deskripsi;
        $data->judul = $request->judul;
        if($request->file('photo'))
        {
            $image = $request->file('photo');
            $new_name = rand() . "-" .$image->getClientOriginalName();
            $image->move("image/event",$new_name);
            $data->photo = $new_name ;
        }
        $data->save();
        return redirect()->route('event.index')->with('success','Event updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        //dd($id);
        $data = $this->model->show($id);
        $data->photo = 'default.png';
        $data->title = 'Event ' .$id;
        $data->desc = 'Event ' .$id;
        $data->deskrips = '';
        $data->judul = '';
        $data->status = 0;
        $data->save();
        return redirect()->route('event.index')->with('success','Event deleted successfully.');
    }
}

resources/views/cms/event/editevent.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Events</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Create Event</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Edit Event {{$data->id}}</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
						</div>
						<div class="card-body collapse in">
            <form action="{{ route('event.update', $data->id) }}" method="POST" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{ method_field('PUT') }}
              <div class="card-block card-dashboard">
                <label><strong>PHOTO</strong></label><br/>
                <img src="/image/event/{{$data->photo}}" style="max-height: 200px; object-fit: cover; width: 100%;" alt="Los Angeles">
                <br/><br/>
                <input name="photo" type="file" />
              </div>
              <div class="card-block card-dashboard">		
                <div class="col-md-12">
                  <!-- <fieldset class="form-group ">
                    <label><strong>Start Date</strong></label>
                    <input type='date' class="form-control" id="datetimepicker4"/>
                  </fieldset> -->
                  <fieldset class="form-group">
                      <label><strong>JUDUL</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="title" value="{{$data->title == 'Event '.$data->id ? '' : $data->title}}">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>DESKRIPSI</strong></label>
                    <textarea id="" class="form-control" name="desc">{{$data->desc == 'Event '.$data->id ? '' : $data->desc}}</textarea>
                  </fieldset> 
                  <fieldset class="form-group">
                      <label><strong>TITLE</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="judul" value="{{$data->judul}}">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>CONTENT</strong></label>
                    <textarea id="" class="form-control" name="deskripsi">{{$data->deskripsi}}</textarea>
                  </fieldset> 
                  <button type="submit" class="btn btn-primary">Submit</button>	
                </div>
							</div>
              </form>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>


<script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>

    <script>
    var konten = document.getElementById("konten")
      CKEDITOR.replace(konten,{
      language:'en-gb'
    })
    CKEDITOR.config.allowedContent = true
</script>
@endsection

resources/views/cms/event/event.blade.php
@extends('layouts.cms')

@section('content')
    <div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Event</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">All Event
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Event</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            @if (session('success'))
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            @endif
                        </div>
						<div class="card-body collapse in">
							<div class="card-block card-dashboard">
                            @foreach($datas as $data)
                                <div class="col-md-4">
                                    <div class="carousel-item">
                                    <label for="input-16"><strong>Event {{$loop->index+1}}</strong></label>
                                    <br/>
                                        <img src="/image/event/{{$data->photo}}" style="max-height: 200px; object-fit: cover; width: 100%;" alt="Los Angeles">
                                        <fieldset>
                                            <label for="input-16">Judul Event : {{$data->title}}</label>
                                        </fieldset> 
                                        <fieldset>
                                            <label for="input-16">Deskripsi Event : {!!str_limit($data->desc,20)!!}</label>
                                            <a href="{{ URL::to('events/' . $data->id) }}" target="_blank" class="btn-read-more">Read More 
                                            <i class="fa fa-angle-right"></i></a>
                                        </fieldset> 
                                        <form action="{{ route('event.destroy', $data->id) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                            <a href="{{ route('event.edit', $data->id) }}" class="btn btn-primary">Edit Event</a>	
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            @endforeach
                            
                            </div>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
<style>
    .carousel-inner {
        width: 100%;
        text-align: center;
        height: 400px;
        background-size: cover;
    }
    .carousel-item {
        background-size: cover;
        width: 100%;
    }
    .carousel-item img {
        text-align: center;
    }
    #demo {
        text-align: center;
    }
    .wrapper-slider {
        text-align: center;
    }
</style>
@endsection