routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//multi language
Route::get('locale', function () {
    return \App::getLocale();
});

Route::get('/locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
});
//
Route::get('/about-cms/section-one', function () {
    return view('cms.about.sectionone');
});
Route::get('/about-cms/section-two', function () {
    return view('cms.about.sectiontwo');
});
Route::get('/about-cms', function () {
    return view('cms.about.about');
});
Route::get('/thankyou', function () {
    return view('front.thanks');
});

Route::get('/', function () {
    // return view('front.comingsoon');
    
    return redirect('home');
});

//front
Route::get('front/{home}', 'FrontController@index');
Route::get('about', 'AboutController@index');
Route::get('home/{home}', 'FrontController@index');
Route::get('/subcategory/{home}', 'CatalogController@subcategory');
Route::get('/category/{home}', 'CatalogController@category');
Route::get('/index/{title}', 'CatalogController@index');
//Route::post('/searchproduct', 'CatalogController@searchproduct');
Route::resource('home','FrontController');
Route::resource('blog','BlogController');
Route::resource('events','EventFrontController');
Route::resource('shop','CatalogController');
Route::resource('catalog','ProductCatalogController');

Route::get('/thanks', function () {
    return view('front.emailthanks');
});
Route::post('send','MailController@send');

Route::get('blog-user', 'PostArticleController@index');
Route::post('sendarticle','PostArticleController@send');
//auth
Auth::routes();
Route::get('/changePassword','ChangePasswordController@showChangePasswordForm');
Route::post('/changePassword','ChangePasswordController@changePassword')->name('changePassword');

//cms
Route::resource('slide','SlideController');
Route::resource('article','ArticleController');
Route::resource('event','EventController');
Route::resource('product','ProductController');
Route::resource('photo','PhotoController');
Route::get('/getsubcategory/{test}','HomeController@getsubcategory');
Route::get('/cms', function () {
    if(Auth::user()->role == 1)
    {
        return redirect('home');
    }
    else
    {
        return view('cms.dashboard');
    }
})->middleware('auth');
//

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $table = 'products';
    protected $fillable = [
        'subcategory_id',
        'title',
        'decs',
        'level',
        'leveldesc',
        'price',
        'type',
        'origin',
        'growth',
        'height',
        'lightdemand',
        'co',
        'item_no',
        'complete',
        'is_hidden'
    ];
    public function subcategory()
    {
        return $this->hasOne('App\Category', 'id', 'subcategory_id');
    }
    public function gallerys()
    {
        return $this->hasMany('App\Gallery', 'product_id', 'id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use App\Product;
use App\Category;
use App\Gallery;
use App\Repositories\Repository;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $model;
    public function __construct(Product $product)
    {
        $this->middleware('auth');
        $this->model = new Repository($product);
    }
    public function index()
    {
        // 
        if(Auth::user()->role == 1)
        {
            return redirect('home');
        }
        else
        {
        $datas = $this->model->all();
        $datas = $datas->where('ishide',0)->where('is_hidden',0);
        return view('cms.product.indexProduct')->with('datas',$datas);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categorys = Category::all();
        return view('cms.product.createProduct')
        ->with('categorys',$categorys);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $this->model->create($request->all());
        $item = strtoupper($data->subcategory->category) .'-0'.$data->id;
        $data->item_no =  $item;
        $data->price = preg_replace('/[^0-9]/','',$request->price);
        $data->save();
        

        if(file_exists($request->file('photo')))
        {
            $image = $request->file('photo');
            $new_name = $data->id."-" .$image->getClientOriginalName();
            //$image->move(public_path("image/gallery",$new_name);
            $image->move("image/gallery",$new_name);

            $gallery = new Gallery([
                'product_id' => $data->id,
                'photo'=>$new_name
            ]);
            $gallery->save();

            $data->complete =  1;
            $data->save();
        }
        return redirect()->route('product.index')->with('success','Product created successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $data = $this->model->show($id);
        // return view('cms.product.createProduct')
        // ->with('data',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $categorys = Category::all();
        $data = $this->model->show($id);
        return view('cms.product.editProduct')
        ->with('data',$data)
        ->with('categorys',$categorys);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data = $this->model->update($request->all(),$id);
        $data = $this->model->show($id);
        $data->price = preg_replace('/[^0-9]/','',$request->price);
        $data->save();
        return redirect()->route('product.index')->with('success','Product updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $data = $this->model->show($id);
        $data->ishide = 1;
        $data->save();
        return redirect()->route('product.index')->with('success','Product deleted successfully.');


    }
}

resources/views/cms/product/createProduct.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Product</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Create Product
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Create New Product</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
						</div>
						<div class="card-body collapse in">
                        <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                        <input type="hidden" value="{{csrf_token()}}" name="_token" />
                        <div class="card-block card-dashboard">			
                            <div class="col-md-12">
                            <fieldset class="form-group">
                                <label>Photo</label>
                                <input name="photo" type="file" />
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>PRODUCT NAME</strong></label>
                                <input type="text" placeholder="Nama Produk" required class="form-control" id="basicInput" name="title">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>PRICE</strong></label>   
                                <div class="input-group">          
                                    <span class="input-group-addon">Rp</span>
                                    <input type="text" id="netprice" required class="form-control no-spinners" placeholder="wajib diisi, jika tidak tahu, masukkan angka 0" name="price" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Net Price">            
                                </div>
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>TYPE</strong></label>
                                <input type="text" class="form-control" id="basicInput" name="type">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>ORIGIN</strong></label>
                                <input type="text" class="form-control" id="basicInput" name="origin">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>GROWTH</strong></label>
                                <input type="text" class="form-control" id="basicInput" name="growth">
                            </fieldset> -->
                            <fieldset class="form-group">
                                <label><strong>SIZE</strong></label>
                                <input type="text" class="form-control" placeholder="contoh: 5cm, 5 inch, 5 meter x 10 meter" id="basicInput" name="height">
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>LIGHT DEMAND</strong></label>
                                <input type="text" class="form-control" id="basicInput" name="lightdemand">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>CO<sup>2</sup></strong></label>
                                <input type="text" class="form-control" id="basicInput" name="co">
                            </fieldset> -->
                            <fieldset class="form-group">
                                <label><strong>DESKRIPSI (ID)</strong></label>
                                <textarea required id="decs" rows="5" class="form-control" name="decs" placeholder="" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="address"></textarea>
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>DESCRIPTION (ENG)</strong></label>
                                <textarea id="decs" rows="5" class="form-control" name="leveldesc" placeholder="" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="address"></textarea>
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>LEVEL</strong></label>
                                <select id="level" name="level" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
                                    <option value="1">Easy</option>
                                    <option value="2">Medium</option>
                                    <option value="3">Advance</option>
                                </select>
                            </fieldset> -->
                           <input type ="hidden" name="level" value = "1">
                            <fieldset class="form-group">
                                <label><strong>CATEGORY</strong></label>
                                <select id="subcategory_id" name="subcategory_id" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
                                    <!-- <option value="">Choose Category</option> -->
                                    @foreach($categorys as $data)
                                        <option value="{{$data->id}}">{{$data->category}}</option>
                                    @endforeach
                                </select>
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>SUB CATEGORY</strong></label>
                                <select id="subcategory" name="subcategory_id" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
                                    <option value=""></option>
                                </select>
                            </fieldset> -->
                            <button type="submit" class="btn btn-primary">Submit</button>	
                            </div>
                            </div>
                        </form>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
//      $(document).ready(function(){
//         $('#category').on('change', function(e){
//            var category_id = e.target.value;
//            $.get('{{ url('getsubcategory') }}/' + category_id, function(data) {
//            //console.log(data);
//            $('#subcategory').empty();
//            $.each(data,function(key, value) {
//             $('#subcategory').append('<option value=' + value.id + '>' + value.category + '</option>');
//             });
//             });
//         });
//       });
    </script>
    <script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>
    
    <script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('app-assets/js/scripts/forms/switch.js') }}" type="text/javascript"></script>
@endsection

resources/views/cms/product/editProduct.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Product</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Edit Product
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Edit Product</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            @if (session('success'))
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            @endif
						</div>
						<div class="card-body collapse in">
                        <form action="{{ route('product.update',$data->id) }}" method="POST" enctype="multipart/form-data">
                        <input type="hidden" value="{{csrf_token()}}" name="_token" />
                        <input type="hidden" name="_method" value="PUT">
                        <div class="card-block card-dashboard">			
                            <div class="col-md-12">
                            <fieldset class="form-group">
                                <label><strong>PRODUCT NAME</strong></label>
                                <input type="text" class="form-control" id="" name="title" value="{{$data->title}}">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>PRICE</strong></label>   
                                <div class="input-group">          
                                    <span class="input-group-addon">Rp</span>
                                    <input type="text" id="netprice" value="{{$data->price}}" class="form-control no-spinners" placeholder="" name="price" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Net Price">            
                                </div>
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>TYPE</strong></label>
                                <input type="text" class="form-control" id="" name="type" value="{{$data->type}}">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>ORIGIN</strong></label>
                                <input value="{{$data->origin}}" type="text" class="form-control" id="" name="origin" >
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>GROWTH RATE</strong></label>
                                <input type="text" class="form-control" id="" name="growth" value="{{$data->growth}}">
                            </fieldset> -->
                            <fieldset class="form-group">
                                <label><strong>SIZE</strong></label>
                                <input type="text" class="form-control" id="" name="height" value="{{$data->height}}">
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>LIGHT DEMAND</strong></label>
                                <input type="text" class="form-control" id="" name="lightdemand" value="{{$data->lightdemand}}">
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>CO<sup>2</sup></strong></label>
                                <input type="text" class="form-control" id="" name="co" value="{{$data->co}}">
                            </fieldset> -->
                            <fieldset class="form-group">
                            
                                <label><strong>DESKRIPSI</strong></label>
                                <textarea required id="decs" rows="5" class="form-control" name="decs" placeholder="" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="address">{{$data->decs}}</textarea>
                            </fieldset>
                            <fieldset class="form-group">
                                <label><strong>DESCRIPTION</strong></label>
                                <textarea id="decs" rows="5" class="form-control" name="leveldesc" placeholder="" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="address">{{$data->leveldesc}}</textarea>
                            </fieldset>
                            <!-- <fieldset class="form-group">
                                <label><strong>LEVEL</strong></label>
                                <select id="level" name="level" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
                                    <option value="1" {{$data->level == '1' ? 'selected' :''}}>Easy</option>
                                    <option value="2" {{$data->level == '2' ? 'selected' :''}}>Medium</option>
                                    <option value="3" {{$data->level == '3' ? 'selected' :''}}>Advance</option>
                                </select>
                            </fieldset> -->
                            <fieldset class="form-group">
                                <label><strong>CATEGORY</strong></label>
                                <select id="subcategory_id" name="subcategory_id" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
                                    @foreach($categorys as $category)
                                        <option value="{{$category->id}}" {{$category->id == $data->subcategory->id ? 'selected' :''}}>{{$category->category}}</option>
                                    @endforeach
                                </select>
                            </fieldset> 
                             <!-- <fieldset class="form-group">
                                <label><strong>SUB CATEGORY</strong></label>
                                <select id="subcategory" name="subcategory_id" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
                                    <option value="{{$data->subcategory->id}}">{{$data->subcategory->category}}</option>
                                </select>
                            </fieldset>  -->

                            <button type="submit" class="btn btn-primary">Submit</button>	
                            </div>
                            </div>
                        </from>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
//      $(document).ready(function(){
//         $('#category').on('change', function(e){
//            var category_id = e.target.value;
//            $.get('{{ url('getsubcategory') }}/' + category_id, function(data) {
//            //console.log(data);
//            $('#subcategory').empty();
//            $.each(data,function(key, value) {
//             $('#subcategory').append('<option value=' + value.id + '>' + value.category + '</option>');
//             });
//             });
//         });
//       });
    </script>
    <script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>
    
    <script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('app-assets/js/scripts/forms/switch.js') }}" type="text/javascript"></script>
@endsection

resources/views/cms/product/indexProduct.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Product</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">List Product
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">List Product</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
              <br/><br/>
              <a href="{{ route('product.create') }}" class="btn btn-primary">Add New Product</a>	
						</div>
						<div class="card-body collapse in">
            <table id="example" class="table table-striped table-bordered table-responsive" style="width:100%">
            <thead>
                <tr>
                    <th colspan="4"><center>Action</center></th>
                    <th>Item No.</th>
                    <th>Product Name</th>
                    <th>Desc</th>
                    <th>Show</th>
                </tr>
            </thead>
            <tbody>
            @foreach($datas as $data)
                <tr>
                    <td><a href="{{ route('product.edit',$data->id) }}" class="btn btn-success btn-md">Edit</a>	</td>
                  
                    <form action="{{ route('product.update',$data->id) }}" method="POST" enctype="multipart/form-data">
                      <input type="hidden" name="_token" value="{{ csrf_token() }}">
                      <input type="hidden" name="_method" value="PUT">
                      <td>
                      <input type="submit" value="{{$data->is_hidden == 0 ? 'Hide' : 'Unhide'}}" name="" class="btn btn-light"  >
                      <input type="hidden" name="id" value="{{$data->id}}">
                      <input type="hidden" name="is_hidden" value="{{$data->is_hidden == 0 ? '1' : '0'}}">
                      </td>
                    </form>
                    <form action="{{ route('product.destroy', $data->id) }}" method="post">
                    {{ csrf_field() }}{{ method_field('DELETE') }}
                    <td><button type="submit" class="btn btn-danger btn-md">Delete</button></a>	</td>
                    </form>
                    <td><a href="{{ route('photo.edit',$data->id) }}" class="btn btn-primary btn-md">Gallery</a>	</td>
                    <td>{{$data->item_no}}</td>
                    <td><a href="{{ route('shop.show',$data->id) }} " target="_blank">{{$data->title}}</a></td>
                    <td>{{str_limit($data->decs,$limit=20)}}</td>
                    <td>{{$data->complete == 1 ? 'Yes' : 'No'}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
	          </div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>

    <script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('app-assets/js/scripts/forms/switch.js') }}" type="text/javascript"></script>

    <!-- javascript and css for table  -->
    
@endsection

resources/views/cms/product/photoProduct.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Photo</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Upload Photo
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">{{$data->title}}</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            @if (session('success'))
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            @endif
                        </div>
						<div class="card-body collapse in">
                            
                            <div class="card-block card-dashboard">
                            <div class="col-md-12">
                            @foreach($data->gallerys as $gallery)
                                <fieldset class="form-group">
                                    <img src="/image/gallery/{{$gallery->photo}}" style="max-height: 200px; object-fit: cover; width: 100%;" alt="Los Angeles">
                                    <form action="{{ route('photo.destroy', $gallery->id) }}" method="post">
                                        {{ csrf_field() }}{{ method_field('DELETE') }}
                                        <td><button type="submit" class="btn btn-danger">Delete</button></a></td>
                                    </form>
                                </fieldset>
                            @endforeach
                            <form action="{{ route('photo.store') }}" method="POST" enctype="multipart/form-data">
                            <input type="hidden" value="{{csrf_token()}}" name="_token" />
                            <br/>
                            <input type="hidden" name="product_id" value="{{$data->id}}">
                                <label>Photo</label>
                                <input name="photo" type="file" />
                            </div>
                            </div>
                            <div class="card-block card-dashboard">	
                            <button type="submit" class="btn btn-primary">Submit</button>	
                            </div>
                            </form>
                        </div>                        
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
    
    <script src="{{asset('app-assets/vendors/js/forms/toggle/bootstrap-checkbox.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('app-assets/vendors/js/forms/toggle/switchery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('app-assets/js/scripts/forms/switch.js') }}" type="text/javascript"></script>
@endsection