routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//multi language
Route::get('locale', function () {
    return \App::getLocale();
});

Route::get('/locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
});
//
Route::get('/about-cms/section-one', function () {
    return view('cms.about.sectionone');
});
Route::get('/about-cms/section-two', function () {
    return view('cms.about.sectiontwo');
});
Route::get('/about-cms', function () {
    return view('cms.about.about');
});
Route::get('/thankyou', function () {
    return view('front.thanks');
});

Route::get('/', function () {
    // return view('front.comingsoon');
    
    return redirect('home');
});

//front
Route::get('front/{home}', 'FrontController@index');
Route::get('about', 'AboutController@index');
Route::get('home/{home}', 'FrontController@index');
Route::get('/subcategory/{home}', 'CatalogController@subcategory');
Route::get('/category/{home}', 'CatalogController@category');
Route::get('/index/{title}', 'CatalogController@index');
//Route::post('/searchproduct', 'CatalogController@searchproduct');
Route::resource('home','FrontController');
Route::resource('blog','BlogController');
Route::resource('events','EventFrontController');
Route::resource('shop','CatalogController');
Route::resource('catalog','ProductCatalogController');

Route::get('/thanks', function () {
    return view('front.emailthanks');
});
Route::post('send','MailController@send');

Route::get('blog-user', 'PostArticleController@index');
Route::post('sendarticle','PostArticleController@send');
//auth
Auth::routes();
Route::get('/changePassword','ChangePasswordController@showChangePasswordForm');
Route::post('/changePassword','ChangePasswordController@changePassword')->name('changePassword');

//cms
Route::resource('slide','SlideController');
Route::resource('article','ArticleController');
Route::resource('event','EventController');
Route::resource('product','ProductController');
Route::resource('photo','PhotoController');
Route::get('/getsubcategory/{test}','HomeController@getsubcategory');
Route::get('/cms', function () {
    if(Auth::user()->role == 1)
    {
        return redirect('home');
    }
    else
    {
        return view('cms.dashboard');
    }
})->middleware('auth');
//

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
    protected $table = 'sliders';
    protected $fillable = [
        'number',
        'photo',
        'status',
        'title',
        'decs',
        'judul',
        'deskripsi'
    ];
}

resources/views/cms/slider/editslide.blade.php
@extends('layouts.cms')

@section('content')
<div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Slide</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Edit Slide</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Edit Slide {{$data->id}}</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
						</div>
						<div class="card-body collapse in">
            <form action="{{ route('slide.update', $data->id) }}" method="POST" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{ method_field('PUT') }}
              <div class="card-block card-dashboard">
                <label><strong>PHOTO</strong></label></br>
                <img src="/image/slide/{{$data->photo}}" style="max-height: 200px; object-fit: cover; width: 100%;" alt="Los Angeles">
                <br/>
                <input name="photo" type="file" />
              </div>
              <div class="card-block card-dashboard">		
                <div class="col-md-12">
                  <!-- <fieldset class="form-group ">
                    <label><strong>Start Date</strong></label>
                    <input type='date' class="form-control" id="datetimepicker4"/>
                  </fieldset> -->
                  <fieldset class="form-group">
                      <label><strong>JUDUL</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="title" value="{{$data->title == 'Slide '.$data->id ? '' : $data->title}}">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>DESKRIPSI</strong></label>
                    <textarea id="" class="form-control" name="decs">{{$data->decs == 'Slide '.$data->id ? '' : $data->decs}}</textarea>
                  </fieldset> 
                  <fieldset class="form-group">
                      <label><strong>TITLE</strong></label>
                      <input type="text" class="form-control" id="basicInput" name="judul" value="{{$data->judul}}">
                  </fieldset>
                  <fieldset class="form-group">
                    <label><strong>CONTENT</strong></label>
                    <textarea id="" class="form-control" name="deskripsi">{{$data->deskripsi}}</textarea>
                  </fieldset> 
                  <button type="submit" class="btn btn-primary">Submit</button>	
                </div>
							</div>
              </form>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>


<script src="{{asset('app-assets/ckeditor/ckeditor.js')}}"></script>

    <script>
    var konten = document.getElementById("konten")
      CKEDITOR.replace(konten,{
      language:'en-gb'
    })
    CKEDITOR.config.allowedContent = true
</script>
@endsection

resources/views/cms/slider/slider.blade.php
@extends('layouts.cms')

@section('content')
    <div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-2">
            <h3 class="content-header-title mb-0">Slider</h3>
            <div class="row breadcrumbs-top">
              <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active">Photo Slider
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-body"><!-- Configuration option table -->
		<section id="configuration">
			<div class="row">
				<div class="col-xs-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Slider</h4>
							<a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            @if (session('success'))
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            @endif
                        </div>
                            <section id="configuration">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="card">
                                       
                                            <div class="card-body collapse in">
                                                <div class="card-block card-dashboard">
                                                @foreach($datas as $data)
                                                    <div class="col-md-4">
                                                        <div class="carousel-item">
                                                        <label for="input-16"><strong>Slider {{$loop->index+1}}</strong></label>
                                                        <br/>
                                                            <img src="/image/slide/{{$data->photo}}" style="max-height: 200px; object-fit: cover; width: 100%;" alt="Los Angeles">
                                                            <fieldset>
                                                                <label for="input-16">Title : {{$data->title}}</label>
                                                            </fieldset> 
                                                            <fieldset>
                                                                <label for="input-16">Desc : {{$data->decs}}</label>
                                                            </fieldset> 
                                                            <form action="{{ route('slide.edit', $data->id) }}" method="post">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                                <a href="{{ route('slide.edit', $data->id) }}" class="btn btn-primary">Edit slide</a>
                                                            </form>
                                                        </div>
                                                    </div>
                                                @endforeach
                                                
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
						</div>
					</div>
				</div>
			</div>
		</section>
        </div>
      </div>
    </div>
<style>
    .carousel-inner {
        width: 100%;
        text-align: center;
        height: 400px;
        background-size: cover;
    }
    .carousel-item {
        background-size: cover;
        width: 100%;
    }
    .carousel-item img {
        text-align: center;
    }
    #demo {
        text-align: center;
    }
    .wrapper-slider {
        text-align: center;
    }
</style>
@endsection